# Generated by Django 4.2.4 on 2023-09-11 14:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_alter_task_options_task_host'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='taks',
            new_name='taskfield',
        ),
    ]
